// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ndypjhbdytqcuenohppd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5keXBqaGJkeXRxY3Vlbm9ocHBkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5MzM3OTUsImV4cCI6MjA1OTUwOTc5NX0.qo-lqqCc3n_CPAMAh1MsL1lePEAY8sC2alsNwdb8Mfc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);