name: 🚀 Feature Request
description: Suggest a new feature for Rhythm Sync
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: dropdown
    id: app
    attributes:
      label: Which app is this for?
      description: Select the app this feature request applies to
      options:
        - Main App (rhythmsync.app)
        - Organizers App (companion app)
        - Shared/Both apps
        - Backend/Database
    validations:
      required: true
  
  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: Describe the feature you'd like to see
      placeholder: What would you like to happen?
    validations:
      required: true
  
  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Explain why you need this feature
      placeholder: Why would this be useful?
    validations:
      required: true
  
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples
      placeholder: Any additional information that might be helpful 